action: fire-dom-event
browser_mod:
  service: browser_mod.popup
  data:
    title: Aquariums
    style: >
      --popup-max-width: calc(385px + 385px);
      --ha-card-border-radius: 0;
    card_mod:
      style:
        layout-card:
          $grid-layout$:
            # card divider border
            .: |
              #root {
                  margin: -24px 0 !important;
              }
            hui-entities-card:
              $: |
                .card-content {
                  padding: var(--tablet-popup-content-padding);
                  padding-bottom: 0.8em;
                }
                ha-card {
                  border-right: 1.5px solid rgba(0, 0, 0, 0.2);
                  border-radius: 0;
                  transition: none;
                }
                /* portrait */
                @media screen and (max-width: 1200px) {
                  ha-card {
                    border-right: none;
                    border-bottom: 1.5px solid rgba(0, 0, 0, 0.2);
                  }
                }
              $hui-horizontal-stack-card:
                # horizontal bottom buttons
                $: |
                  #root {
                    justify-content: space-evenly;
                    margin-top: 1.7em;
                    max-width: 82vw; /* iphonex */
                  }
                  #root > * {
                    flex: 0 1 auto !important;
                  }
    content:
      type: custom:layout-card
      layout_type: custom:grid-layout
      layout:
        margin: 0
        grid-template-columns: 385px 385px
        grid-template-rows: 1fr
        grid-template-areas: |
          "bookcase _140l"
        mediaquery:
          #portrait
          "(max-width: 1200px)":
            grid-template-columns: 1fr
            grid-template-rows: repeat(3, 1fr)
            grid-template-areas: |
              "bookcase"
              "_140l"
      cards:

        ### HOME ASSISTANT

        # - type: entities
        #   view_layout:
        #     grid-area: hass
        #   title: Home Assistant
        #   show_header_toggle: false
        #   card_mod:
        #     class: header
        #   entities:
        #     - entity: sensor.current_version
        #       name: Installerad
        #       icon: mdi:home-assistant

        #     - entity: switch.docker_watchtower
        #       name: Watchtower
        #       icon: cil:docker-watchtower

        #     - entity: sensor.template_hass_next_release

        #     - entity: sensor.databas
        #       icon: mdi:database

        #     - entity: sensor.home_assistant_log_size
        #       name: Loggfil
        #       icon: mdi:file-document

        #     - type: attribute
        #       entity: sensor.docker_home_assistant
        #       attribute: uptime
        #       format: relative
        #       name: Senast omstart
        #       icon: mdi:update

        #     - type: custom:bar-card
        #       width: 55%
        #       height: 2em
        #       decimal: 0
        #       unit_of_measurement: '%'
        #       positions: &bar_card_positions
        #         icon: outside
        #         indicator: 'off'
        #         name: outside
        #       severity: &bar_card_severity
        #         - color: '#6d2525'
        #           from: 85
        #           to: 999
        #       entity_row: true
        #       entities:

        #         - entity: sensor.docker_home_assistant
        #           attribute: cpu_percentage
        #           name: Processor
        #           icon: mdi:chip

        #         - entity: sensor.docker_home_assistant
        #           attribute: memory_percentage
        #           name: Minne
        #           icon: mdi:memory

        #     - type: custom:hui-horizontal-stack-card
        #       cards:
        #         - type: custom:button-card
        #           name: Serveromstart
        #           icon: mdi:reload
        #           tap_action:
        #             action: call-service
        #             service: browser_mod.sequence
        #             service_data:
        #               sequence:
        #                 - service: browser_mod.notification
        #                   data:
        #                     message: Startar om server...
        #                 - service: browser_mod.delay
        #                   data:
        #                     time: 3000
        #                 - service: homeassistant.restart
        #           template: icon_name

        #         - type: custom:button-card
        #           name: Container
        #           icon: mdi:reload
        #           tap_action:
        #             action: call-service
        #             service: browser_mod.sequence
        #             service_data:
        #               sequence:
        #                 - service: browser_mod.notification
        #                   data:
        #                     message: Startar om container...
        #                 - service: homeassistant.save_persistent_states
        #                 - service: browser_mod.delay
        #                   data:
        #                     time: 3000
        #                 - service: shell_command.restart_container
        #           template: icon_name

        # BOOKCASE TANK
        - type: entities
          view_layout:
            grid-area: bookcase
          title: Bookcase Tank
          state_color: true
          show_header_toggle: false
          card_mod:
            class: header
          entities:

            - type: custom:mushroom-entity-card
              entity: switch.fish_light
              name: Light
              icon: mdi:led-strip
              tap_action:
                action: toggle
            
            - type: custom:mushroom-entity-card
              entity: switch.fish_pump
              name: Pump
              icon: mdi:water-pump
              fill_container: true
              tap_action:
                action: toggle
            
            - type: custom:mushroom-entity-card
              entity: switch.fish_co2
              name: CO2
              icon: mdi:molecule-co2
              tap_action:
                action: toggle

            - type: custom:mushroom-entity-card
              entity: sensor.bookcase_last_feed_time
              name: Last feed

            - entity: timer.bookcase_tank_feed
            
            - type: custom:hui-horizontal-stack-card
              cards:
                - type: conditional
                  conditions:
                    - entity: timer.bookcase_tank_feed
                      state: idle
                  card:
                    type: custom:button-card
                    name: Feed
                    icon: mdi:shaker
                    tap_action:
                      action: call-service
                      service: script.bookcase_feed
                    template: icon_name
                
                - type: conditional
                  conditions:
                    - entity: timer.bookcase_tank_feed
                      state: active
                  card:
                    type: custom:button-card
                    name: Cancel
                    icon: mdi:cancel
                    tap_action:
                      action: call-service
                      service: timer.cancel
                      service_data:
                        entity_id: timer.bookcase_tank_feed
                    template: icon_name

        # 140L TANK
        - type: entities
          view_layout:
            grid-area: _140l
          title: 140L Tank
          state_color: true
          show_header_toggle: false
          card_mod:
            class: header
          entities:

            - type: custom:mushroom-entity-card
              entity: switch.tank_light
              name: Light
              icon: mdi:led-strip
              tap_action:
                action: toggle
            
            - type: custom:mushroom-entity-card
              entity: switch.tank_pump
              name: Pump
              icon: mdi:water-pump
              fill_container: true
              tap_action:
                action: toggle
            
            - type: custom:mushroom-entity-card
              entity: switch.tank_co2
              name: CO2
              icon: mdi:molecule-co2
              tap_action:
                action: toggle

            - type: custom:mushroom-entity-card
              entity: sensor.140l_last_feed_time
              name: Last feed

            - entity: timer.140l_tank_feed
            
            - type: custom:hui-horizontal-stack-card
              cards:
                - type: conditional
                  conditions:
                    - entity: timer.140l_tank_feed
                      state: idle
                  card:
                    type: custom:button-card
                    name: Feed
                    icon: mdi:shaker
                    tap_action:
                      action: call-service
                      service: script.140l_feed
                    template: icon_name
                
                - type: conditional
                  conditions:
                    - entity: timer.140l_tank_feed
                      state: active
                  card:
                    type: custom:button-card
                    name: Cancel
                    icon: mdi:cancel
                    tap_action:
                      action: call-service
                      service: timer.cancel
                      service_data:
                        entity_id: timer.140l_tank_feed
                    template: icon_name
