external_url: 
tplink_strip_ips: 
  # - host: 192.168.40.15
http_trusted_proxies:
  # - 192.168.0.0/24
# Maria db url
recorder_db_url: 
# InfluxDB
influxdb_host: 
influxdb_port: 
influxdb_token: 
influxdb_organization:
influxdb_bucket:
# Smart meter topics
smart_meter_electricity_power_topic: "glow/<device-mac-address>/SENSOR/electricitymeter"
smart_meter_gas_power_topic: "glow/<device-mac-address>/SENSOR/gasmeter"